# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 951bf6a2ad3a8159ba25fb685f1bd818236d4fa0ac5af1f608db8e0dd5b5f3727324997af8af54ffaf023e0fc387a47ab16364460a7239d66c2033766e32aaa9

test:
  secret_key_base: 9f4b821815c5f19b47f1e539aa62f42295203b1ac3c06968214fe3f0d91ed5972b50e8bce2d092d80b3e1f8362ce4ea58c1cd51842fffe401c7218062178992c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
